### ISSUE TITLE
Returning a 404 instead of 403 with invalid key

### ISSUE THREAD

**Issue by juliemuraski** [BestBuyAPIs/bby-query-builder#146]
Value from same query into Remix (403)

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<h1>
     <script id="tinyhippos-injected"/>
     Developer Inactive
</h1>

Value from QB
[
  {
    "error": {
      "status": 404,
      "config": {
        "method": "JSONP",
        "transformRequest": [
          null
        ],
        "transformResponse": [
          null
        ],
        "url": "https://api.remix.bestbuy.com/v1/products?apiKey=rbda762vjychtktzbj8kdcn5&callback=JSON_CALLBACK&format=json",
        "headers": {
          "Accept": "application/json, text/plain, */*"
        }
      },
      "statusText": "error"
    }
  }
]

**Comment by cmlizama** [comment]
I did some reading and it seems like this is a limitation of the ng-resource function that returns a promise. We have to use ng-resource/jsonp to make a request from our client to the remix server (instead of an app where our own app server makes a request to remix.) The problem is that the ng-resource request is not exactly an AJAX/XHR style request where you can get back a status code, it's more like a <script> tag where it either loads or it doesn't, so this is why it does a 404 not found error instead of the 403.

**Comment by cmlizama** [comment]
Actually to be fair to angular, it is more of a limitation with JSONP than anything else.
